name: Build Windows Application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        # تم تعديل هذا السطر ليصبح أكثر موثوقية
        run: python -m PyInstaller DarkForge_Master_Pipeline.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-application
          path: dist/
